# Generated by Django 5.2.14 on 2026-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('SKILL_ADDED', 'Skill Added'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROFILE_UPDATED', 'Profile Updated'), ('REPO_IMPORTED', 'Repo Imported'), ('PROJECT_COMPLETED', 'Project Completed'), ('PROJECT_IN_PROGRESS', 'Project In Progress'), ('SKILL_SYNC', 'Skill Telemetry Synchronized'), ('SKILL_REMOVED', 'Skill Removed')], max_length=50),
        ),
    ]
