# Generated by Django 5.2.14 on 2026-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
