# Generated by Django 5.2.14 on 2026-05-14 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='featured_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on_profiles', to='users.badge'),
        ),
    ]
