# Generated by Django 5.2.14 on 2026-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_featured_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbadge',
            name='is_showcased',
            field=models.BooleanField(default=False),
        ),
    ]
