# Generated by Django 5.2.14 on 2026-05-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userbadge_is_showcased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
