# Generated by Django 5.2.14 on 2026-05-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_avatar_base64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='depth_score',
            new_name='dev_score',
        ),
    ]
