# Generated by Django 5.2.14 on 2026-05-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_depth_score_userprofile_dev_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dev_score',
            new_name='depth_score',
        ),
    ]
