# Generated by Django 5.2.14 on 2026-05-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_dev_score_userprofile_depth_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gfg_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
