# Generated by Django 5.2.14 on 2026-05-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_gfg_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gfg_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leetcode_username',
        ),
    ]
