# Generated by Django 5.2.14 on 2026-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='hours_practiced',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
