# Generated by Django 5.2.14 on 2026-05-14 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_userskill_hours_practiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='started_learning_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
